# Generated by Django 5.2.4 on 2025-07-26 18:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(default=0, help_text='Total amount of the invoice. Stored as integer, e.g., in cents/paise.')),
                ('paid_on_date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='List of contact phone numbers for the vendor.', null=True, size=None)),
                ('address', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True, help_text='Any additional remarks about the vendor.')),
            ],
        ),
        migrations.CreateModel(
            name='VendorRole',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('measurement_type', models.CharField(choices=[('Shoulder', 'Shoulder'), ('Chest', 'Chest'), ('Waist', 'Waist'), ('Hip', 'Hip'), ('Length', 'Length'), ('Sleeve', 'Sleeve')], max_length=20)),
                ('value', models.JSONField(blank=True, help_text='Stores measurement values in JSON format.', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_tracker.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_placed_on', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('completion_date', models.DateField(blank=True, help_text='Date when the order was completed.', null=True)),
                ('amount', models.IntegerField(default=0, help_text='Total calculated amount for the order. Stored as integer, e.g., in cents/paise.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_tracker.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='production_tracker.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Particulars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name or description of the particular item.', max_length=255)),
                ('amount', models.IntegerField(help_text='Amount for this particular item. Stored as integer, e.g., in cents/paise.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particulars', to='production_tracker.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_tracker.order')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_tracker.pipelinestage')),
                ('assigned_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_tracker.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_tracker.vendorrole'),
        ),
    ]
