# Generated by Django 5.2.4 on 2025-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='particulars',
            name='details',
            field=models.CharField(blank=True, help_text='Additional details about the particular item.', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='particulars',
            name='name',
            field=models.CharField(help_text='Name or description of the particular item.', max_length=20),
        ),
    ]
