# Generated by Django 5.2.4 on 2025-07-26 19:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(choices=[('Pant', 'Pant'), ('Shirt', 'Shirt'), ('Suite', 'Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, help_text='List of contact phone numbers for the vendor.', null=True, size=None),
        ),
    ]
